menubar: 
min_height: 400
toolbar:
  - styleselect | bold italic underline | undo redo | forecolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table
  - image | link | preview code | fontselect
plugins:
  - image
  - link
  - textcolor
  - table
  - preview 
  - template 
  - wordcount 
  - code
templates: [
    { title: 'test', content: '<h1>Test 1</h1>'}
    ]

font_formats: "Roboto=Roboto;Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;Comic Sans MS=comic sans ms,sans-serif;Courier New=courier new,courier;Georgia=georgia,palatino;Helvetica=helvetica;Impact=impact,chicago;Symbol=symbol;Tahoma=tahoma,arial,helvetica,sans-serif;Terminal=terminal,monaco;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva;Webdings=webdings;Wingdings=wingdings,zapf dingbats"    